# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import phonebook_pb2 as phonebook__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in phonebook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhonebookStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddEntry = channel.unary_unary(
                '/phonebook.Phonebook/AddEntry',
                request_serializer=phonebook__pb2.AddRequest.SerializeToString,
                response_deserializer=phonebook__pb2.AddResponse.FromString,
                _registered_method=True)
        self.GetNumber = channel.unary_unary(
                '/phonebook.Phonebook/GetNumber',
                request_serializer=phonebook__pb2.GetRequest.SerializeToString,
                response_deserializer=phonebook__pb2.GetResponse.FromString,
                _registered_method=True)
        self.EditEntry = channel.unary_unary(
                '/phonebook.Phonebook/EditEntry',
                request_serializer=phonebook__pb2.EditRequest.SerializeToString,
                response_deserializer=phonebook__pb2.EditResponse.FromString,
                _registered_method=True)
        self.DeleteEntry = channel.unary_unary(
                '/phonebook.Phonebook/DeleteEntry',
                request_serializer=phonebook__pb2.DeleteRequest.SerializeToString,
                response_deserializer=phonebook__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListEntries = channel.unary_unary(
                '/phonebook.Phonebook/ListEntries',
                request_serializer=phonebook__pb2.ListEntriesRequest.SerializeToString,
                response_deserializer=phonebook__pb2.ListEntriesResponse.FromString,
                _registered_method=True)


class PhonebookServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhonebookServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEntry,
                    request_deserializer=phonebook__pb2.AddRequest.FromString,
                    response_serializer=phonebook__pb2.AddResponse.SerializeToString,
            ),
            'GetNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumber,
                    request_deserializer=phonebook__pb2.GetRequest.FromString,
                    response_serializer=phonebook__pb2.GetResponse.SerializeToString,
            ),
            'EditEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.EditEntry,
                    request_deserializer=phonebook__pb2.EditRequest.FromString,
                    response_serializer=phonebook__pb2.EditResponse.SerializeToString,
            ),
            'DeleteEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntry,
                    request_deserializer=phonebook__pb2.DeleteRequest.FromString,
                    response_serializer=phonebook__pb2.DeleteResponse.SerializeToString,
            ),
            'ListEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntries,
                    request_deserializer=phonebook__pb2.ListEntriesRequest.FromString,
                    response_serializer=phonebook__pb2.ListEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phonebook.Phonebook', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phonebook.Phonebook', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Phonebook(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/AddEntry',
            phonebook__pb2.AddRequest.SerializeToString,
            phonebook__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/GetNumber',
            phonebook__pb2.GetRequest.SerializeToString,
            phonebook__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/EditEntry',
            phonebook__pb2.EditRequest.SerializeToString,
            phonebook__pb2.EditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/DeleteEntry',
            phonebook__pb2.DeleteRequest.SerializeToString,
            phonebook__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.Phonebook/ListEntries',
            phonebook__pb2.ListEntriesRequest.SerializeToString,
            phonebook__pb2.ListEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
