# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: phonebook.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'phonebook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fphonebook.proto\x12\tphonebook\"?\n\nAddRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\x05\"a\n\x0b\x41\x64\x64Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06number\x18\x04 \x01(\t\x12\x12\n\nexpires_at\x18\x05 \x01(\x03\"\x1a\n\nGetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"1\n\x0bGetResponse\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\"u\n\x0b\x45\x64itRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\nnew_number\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0fnew_ttl_seconds\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\r\n\x0b_new_numberB\x12\n\x10_new_ttl_seconds\"\\\n\x0c\x45\x64itResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nnew_number\x18\x03 \x01(\t\x12\x16\n\x0enew_expires_at\x18\x04 \x01(\x03\"\x1d\n\rDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12ListEntriesRequest\"9\n\x05\x45ntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\"8\n\x13ListEntriesResponse\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.phonebook.Entry2\xd2\x02\n\tPhonebook\x12\x39\n\x08\x41\x64\x64\x45ntry\x12\x15.phonebook.AddRequest\x1a\x16.phonebook.AddResponse\x12:\n\tGetNumber\x12\x15.phonebook.GetRequest\x1a\x16.phonebook.GetResponse\x12<\n\tEditEntry\x12\x16.phonebook.EditRequest\x1a\x17.phonebook.EditResponse\x12\x42\n\x0b\x44\x65leteEntry\x12\x18.phonebook.DeleteRequest\x1a\x19.phonebook.DeleteResponse\x12L\n\x0bListEntries\x12\x1d.phonebook.ListEntriesRequest\x1a\x1e.phonebook.ListEntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phonebook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=30
  _globals['_ADDREQUEST']._serialized_end=93
  _globals['_ADDRESPONSE']._serialized_start=95
  _globals['_ADDRESPONSE']._serialized_end=192
  _globals['_GETREQUEST']._serialized_start=194
  _globals['_GETREQUEST']._serialized_end=220
  _globals['_GETRESPONSE']._serialized_start=222
  _globals['_GETRESPONSE']._serialized_end=271
  _globals['_EDITREQUEST']._serialized_start=273
  _globals['_EDITREQUEST']._serialized_end=390
  _globals['_EDITRESPONSE']._serialized_start=392
  _globals['_EDITRESPONSE']._serialized_end=484
  _globals['_DELETEREQUEST']._serialized_start=486
  _globals['_DELETEREQUEST']._serialized_end=515
  _globals['_DELETERESPONSE']._serialized_start=517
  _globals['_DELETERESPONSE']._serialized_end=550
  _globals['_LISTENTRIESREQUEST']._serialized_start=552
  _globals['_LISTENTRIESREQUEST']._serialized_end=572
  _globals['_ENTRY']._serialized_start=574
  _globals['_ENTRY']._serialized_end=631
  _globals['_LISTENTRIESRESPONSE']._serialized_start=633
  _globals['_LISTENTRIESRESPONSE']._serialized_end=689
  _globals['_PHONEBOOK']._serialized_start=692
  _globals['_PHONEBOOK']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
